// Code generated by "stringer -type=GPUBlobMem"; DO NOT EDIT.

package virtio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIRTIO_GPU_BLOB_MEM_GUEST-1]
	_ = x[VIRTIO_GPU_BLOB_MEM_HOST3D-2]
	_ = x[VIRTIO_GPU_BLOB_MEM_HOST3D_GUEST-3]
}

const _GPUBlobMem_name = "VIRTIO_GPU_BLOB_MEM_GUESTVIRTIO_GPU_BLOB_MEM_HOST3DVIRTIO_GPU_BLOB_MEM_HOST3D_GUEST"

var _GPUBlobMem_index = [...]uint8{0, 25, 51, 83}

func (i GPUBlobMem) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_GPUBlobMem_index)-1 {
		return "GPUBlobMem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GPUBlobMem_name[_GPUBlobMem_index[idx]:_GPUBlobMem_index[idx+1]]
}
