// Code generated by "stringer -type=GPUFormat"; DO NOT EDIT.

package virtio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIRTIO_GPU_FORMAT_B8G8R8A8_UNORM-1]
	_ = x[VIRTIO_GPU_FORMAT_B8G8R8X8_UNORM-2]
	_ = x[VIRTIO_GPU_FORMAT_A8R8G8B8_UNORM-3]
	_ = x[VIRTIO_GPU_FORMAT_X8R8G8B8_UNORM-4]
	_ = x[VIRTIO_GPU_FORMAT_R8G8B8A8_UNORM-67]
	_ = x[VIRTIO_GPU_FORMAT_X8B8G8R8_UNORM-68]
	_ = x[VIRTIO_GPU_FORMAT_A8B8G8R8_UNORM-121]
	_ = x[VIRTIO_GPU_FORMAT_R8G8B8X8_UNORM-134]
}

const (
	_GPUFormat_name_0 = "VIRTIO_GPU_FORMAT_B8G8R8A8_UNORMVIRTIO_GPU_FORMAT_B8G8R8X8_UNORMVIRTIO_GPU_FORMAT_A8R8G8B8_UNORMVIRTIO_GPU_FORMAT_X8R8G8B8_UNORM"
	_GPUFormat_name_1 = "VIRTIO_GPU_FORMAT_R8G8B8A8_UNORMVIRTIO_GPU_FORMAT_X8B8G8R8_UNORM"
	_GPUFormat_name_2 = "VIRTIO_GPU_FORMAT_A8B8G8R8_UNORM"
	_GPUFormat_name_3 = "VIRTIO_GPU_FORMAT_R8G8B8X8_UNORM"
)

var (
	_GPUFormat_index_0 = [...]uint8{0, 32, 64, 96, 128}
	_GPUFormat_index_1 = [...]uint8{0, 32, 64}
)

func (i GPUFormat) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _GPUFormat_name_0[_GPUFormat_index_0[i]:_GPUFormat_index_0[i+1]]
	case 67 <= i && i <= 68:
		i -= 67
		return _GPUFormat_name_1[_GPUFormat_index_1[i]:_GPUFormat_index_1[i+1]]
	case i == 121:
		return _GPUFormat_name_2
	case i == 134:
		return _GPUFormat_name_3
	default:
		return "GPUFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
